# Generated by Django 4.1.5 on 2023-02-13 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_betakey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.CharField(choices=[('TU', 'Thumbs-up'), ('TD', 'Thumbds-down'), ('TN', 'Neutral')], default='TN', max_length=2)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('skeleton', models.TextField()),
                ('num_tokens', models.IntegerField()),
                ('num_searched', models.IntegerField(default=1)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_string', models.TextField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('queries', models.ManyToManyField(to='api.query')),
            ],
        ),
        migrations.CreateModel(
            name='SERPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('serp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.serp')),
            ],
        ),
        migrations.AddField(
            model_name='unfiniteuser',
            name='is_beta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unfiniteuser',
            name='register_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.query'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
