# Generated by Django 4.1.5 on 2023-02-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback_query_serp_serpitem_unfiniteuser_is_beta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serp',
            name='entries',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
