# Generated by Django 4.1.5 on 2023-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_queryfeedback_user_alter_serpfeedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serpfeedback',
            name='resource',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serpfeedback',
            name='rating',
            field=models.CharField(choices=[('TU', 'Thumbs-up'), ('TD', 'Thumbs-down'), ('TN', 'Neutral')], default='TN', max_length=2),
        ),
    ]
