# Generated by Django 4.1.5 on 2023-03-04 20:22

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_serpfeedback_resource_alter_serpfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betakey',
            name='key',
            field=models.CharField(default=api.models.get_key, max_length=64),
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.TextField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.query')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
