# Generated by Django 4.1.5 on 2023-03-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_betakey_key_completion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryFeedback',
            new_name='Feedback',
        ),
    ]
