# Generated by Django 4.1.5 on 2023-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='serp',
            name='idx',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serpfeedback',
            name='serp_idx',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serpfeedback',
            name='topic_idx',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unfiniteuser',
            name='in_progress',
            field=models.ManyToManyField(null=True, to='api.query'),
        ),
    ]
