# Generated by Django 4.1.5 on 2023-03-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_serp_idx_serpfeedback_serp_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unfiniteuser',
            name='in_progress',
            field=models.ManyToManyField(to='api.query'),
        ),
    ]
