# Generated by Django 4.1.5 on 2023-03-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_unfiniteuser_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='track',
            field=models.BooleanField(default=False),
        ),
    ]
