# Generated by Django 4.1.5 on 2023-03-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_unfiniteuser_in_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevantquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(default=None)),
                ('questions', models.TextField()),
                ('num_searched', models.IntegerField(default=1)),
                ('generation_prompt', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.query')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('questionidx', models.IntegerField()),
                ('summary', models.TextField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.query')),
            ],
        ),
    ]
