# Generated by Django 4.1.7 on 2023-03-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_questionsummary_urlidx_questionsummary_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsummary',
            name='answertype',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
