# Generated by Django 4.1.7 on 2023-05-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_questionsummary_answertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="unfiniteuser",
            name="is_fm",
            field=models.BooleanField(default=False),
        ),
    ]
