# Generated by Django 4.1.5 on 2023-04-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_questionsummary_answertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='unfiniteuser',
            name='is_fm',
            field=models.BooleanField(default=False),
        ),
    ]
