# Generated by Django 4.1.5 on 2023-04-18 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dochandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.CharField(default='dd0ea6540ef94201', editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='QuestionEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('event_message', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
