# Generated by Django 4.1.7 on 2023-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochandler', '0002_feedbackmodel_thread_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='txttosummarize',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.TextField(default='7d965247e21c4d5d', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='promptmessages',
            field=models.TextField(blank=True, default='[[0, "You are an expert summarizer and teacher."], [0, "Please summarize the following texts into a short and coherent answer to the question. Make the answer accessible, break it down into points and keep paragraphs short where you can."], [0, "Instructions: \\n\\t1. Structure the answer into multiple paragraphs where necessary.\\n    2. If the attached text is not relevant, please say you couldn\'t find the answer."]]', null=True),
        ),
    ]
