# Generated by Django 4.1.5 on 2023-04-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochandler', '0003_qa_txttosummarize_alter_thread_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_pages',
            new_name='document_chunks',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='num_pages',
            new_name='num_chunks',
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.TextField(default='b8c966a516ec4d40', editable=False, primary_key=True, serialize=False),
        ),
    ]
