# Generated by Django 4.1.5 on 2023-04-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochandler', '0007_alter_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.CharField(default='9c2e2745fcb84c17', editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
