# Generated by Django 4.1.5 on 2023-04-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochandler', '0010_document_embedded_document_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(max_length=400, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.CharField(default='afb4c0d7fe434b33', editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
