# Generated by Django 4.1.7 on 2023-04-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dochandler", "0011_alter_document_url_alter_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="id",
            field=models.CharField(
                default="6fdc3cedd7004fa3",
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
