# Generated by Django 4.1.7 on 2023-04-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dochandler", "0012_alter_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="id",
            field=models.CharField(
                default="bd3ef02799d94441",
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
