# Generated by Django 4.1.5 on 2023-05-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dochandler", "0013_alter_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="qa",
            name="relevantquestions",
            field=models.TextField(default="[]"),
        ),
        migrations.AlterField(
            model_name="thread",
            name="id",
            field=models.CharField(
                default="6e84f597e34c42e2",
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="promptmessages",
            field=models.TextField(
                blank=True,
                default='[[0, "You are an expert summarizer and teacher."], [0, "Please summarize the following texts into a short and coherent answer to the question. Make the answer accessible, break it down into points and keep paragraphs short where you can."], [0, "Instructions: \\n    1. If the attached text is not relevant, please say you couldn\'t find the answer."]]',
                null=True,
            ),
        ),
    ]
