# Generated by Django 4.1.7 on 2023-05-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dochandler", "0014_qa_relevantquestions_alter_thread_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="outline",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="id",
            field=models.CharField(
                default="4ef006ec9b594f5f",
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="promptmessages",
            field=models.TextField(blank=True, default="[]", null=True),
        ),
    ]
