# Generated by Django 4.1.7 on 2023-05-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dochandler", "0015_document_outline_alter_thread_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="id",
            field=models.CharField(
                default="86a2473d03dc4627",
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
