# Generated by Django 4.1.7 on 2023-05-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dochandler", "0015_remove_qa_relevantquestions_alter_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="qa",
            name="relevantquestions",
            field=models.TextField(default="[]"),
        ),
        migrations.AlterField(
            model_name="thread",
            name="id",
            field=models.CharField(
                default="0dc616dff1614ab9",
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
