# Generated by Django 4.1.7 on 2023-05-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dochandler", "0016_alter_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="id",
            field=models.CharField(
                default="2e8b4842e3cc4cd1",
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
